// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHLwQlwrZ81dOG4juMU087wjy8Ws6z9bo',
    appId: '1:134006276178:web:f85df65593b45bdd855f8b',
    messagingSenderId: '134006276178',
    projectId: 'drug-test-app',
    authDomain: 'drug-test-app.firebaseapp.com',
    storageBucket: 'drug-test-app.firebasestorage.app',
    measurementId: 'G-LLP63DDC8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYSZI5cfCZSaOviEz0MkxuNj3lZCV7eHc',
    appId: '1:134006276178:android:7bc4bf9f0093e4dc855f8b',
    messagingSenderId: '134006276178',
    projectId: 'drug-test-app',
    storageBucket: 'drug-test-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmCzWFqFS7Fc6-42WX6cf1Miko2vzm5qw',
    appId: '1:134006276178:ios:e5aef6c44261bf93855f8b',
    messagingSenderId: '134006276178',
    projectId: 'drug-test-app',
    storageBucket: 'drug-test-app.firebasestorage.app',
    iosBundleId: 'com.example.drugTestApp',
  );
}
